name: Bygg og publiser kokebok

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Hent kildekoden
        uses: actions/checkout@v7

      - name: Installer Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm

      - name: Installer pakker
        run: npm ci

      - name: Bygg prosjektet
        run: npm run build

      - name: Konfigurer GitHub Pages
        uses: actions/configure-pages@v6

      - name: Last opp produksjonsbygget
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./dist

      - name: Publiser GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5